server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/product_pricing_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

fileBaseUrl: http://localhost:9090/api

file:
  storage-dir: D:/Software/IntelliJIDEA2025.3.2/Projects/ProductsPricingSystem/files

model:
  base-path: D:/Software/IntelliJIDEA2025.3.2/Projects/ProductsPricingSystem/deepLearning/models

python:
  executable: python
  script:
    path: D:/Software/IntelliJIDEA2025.3.2/Projects/ProductsPricingSystem/deepLearning/yolov8/predict_upload.py

conda:
  env:
    name: yolov8

temp:
  image:
    dir: D:/Software/IntelliJIDEA2025.3.2/Projects/ProductsPricingSystem/temp_upload_images
    prefix: uploaded_image

app:
  cors:
    allowed-origins:
      - http://localhost:9091
