server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

detection:
  process:
    timeout: 60

app:
  default-user-avatar: /files/download/默认头像.jpg
